import Head from "next/head";
import Image from "next/image";
import { LockClosedIcon } from "@heroicons/react/solid";

export default function Home() {
  return (
    <div className="h-screen bg-gray-50">
      <Head>
        <title>Brain Bank</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="min-h-full flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
          <img
            className="mx-auto h-32 w-auto"
            src="/1F9E0.svg"
            alt="Workflow"
          />
        </div>
      </main>
    </div>
  );
}
